spring:
  profiles:
    active: core

websocket:
  port: 9080
  path: /websocket

tcp:
  backlog: 1024
  keepalive: true
  noDelay: true

ssl:
  certpath: nebulamooc.pem
  keypath: nebulamooc.key

port:
  http: 8080
  https: 8443

server:
  port: ${port.https}
  ssl:
    #证书的路径
    key-store: classpath:nebulamooc.pfx
    #证书密码
    key-store-password: 4qDeSwsh
    #秘钥库类型
    key-store-type: PKCS12

